on: 
  push:
    branches:
      - master






jobs:
  build: 
    run-on: ubuntu-latest

    steps:
      - name: 'Testing Github action'
        run: pwd

      - name: 'Printing Folder Contents'
        run: ls
